### ISSUE TITLE
Start Building Another Web3API Client

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/roadmap#41]
Languages to consider:
- Rust
- C/C++
- Python
- Go

NOTE: Rust may give us the biggest "bang for our buck", as it can be compiled into a native library (static or dynamic), which can then be used in the other languages listed. We'd simply need to create a simple wrapper around them to make it more user friendly using the languages native syntax.

**Comment by rihp** [comment]
we have started building a Rust client with the help of a new developer @kobby-pentangeli 👏
